### ISSUE TITLE
[GUM] Shortcut Suggestions

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#205]
Add standard windows shortcuts for things.

- [x] 1. Redo (CTRL+Y) (See #271 )
- [x] 2. F2 (Rename a control/component/screen/instance) (See #419)  This could simply just set focus on the Name variable in the Variables perhaps
- [x] 3. (Zoom the UI of Gum.exe, a bit small on my large screen and resolution and hard to see)  CTRL PLUS and CTRL Minus  (See #420)
- [x] 4. Show/Hide tools (CTRL+H or something), pressing once hides, pressing a second time shows.

**Comment by kaltinril** [comment]
I pulled our Redo because I ran into it again and it was frustrating.  #271

**Comment by kaltinril** [comment]
Moved F2 to it's own issue #419

**Comment by kaltinril** [comment]
the 4th item "Show/HIde" has been enhanced greatly, I'd consider it basically complete.

**Comment by kaltinril** [comment]
I've pulled out the 3rd item into #420
