### ISSUE TITLE
Gum should have a smoother animation workflow

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#53]
The Gum workflow for animation is inefficient. This is what the current workflow looks like:

1. Create states for a component
    - right click states to duplicate as copy/paste doesn't work
    - right click duplicated state again to rename
1. Open the animation editor window
   - resize animation editor to see state names because it's always too small
   - resize Gum to make room for the animation editor as a separate window
1. Add states and adjust timings and interpolations
1. Decide what edits need to be made to states after roughing in timings
1. Close animation editor window because you can't edit states while it's open or bad things happen
1. Repeat process

The constant right clicking to make states, constant opening and closing of editor, constant resizing of editor window, and need to perform these steps in a loop to fine tune animations has a lot of wasted steps. The following things would improve this workflow significantly:

- [x] [It should be possible to copy/paste states within a category](https://github.com/vchelaru/Gum/issues/48)
- [x] [Pressing F2 or double clicking a state should open rename dialog or rename in place](https://github.com/vchelaru/Gum/issues/49)
- [x] [The animation editor should be a tab within Gum like the Texture Coordinates tab](https://github.com/vchelaru/Gum/issues/50)
- [x] [Gum should allow you to edit states while working on an animation](https://github.com/vchelaru/Gum/issues/51)
- [x] [Gum should allow you to swap a state for a different state](https://github.com/vchelaru/Gum/issues/52)

**Comment by vchelaru** [comment]
All items are done.
